image: "ruby:2.3"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

stages:
  - bundle
  - publish

build:
  stage: bundle
  script

pages:
  stage: publish
  before_script:
  script:
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
