stages:
  - bundle
  - publish

build:
  stage: bundle
  script:
    - hugo
  artifacts:
    paths:
      - build
  image: monachus/hugo

pages:
  stage: publish
  before_script:
  script:
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
  image: alpine
