image: "ruby:slim-buster"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby
    
stages:
  - bundle

bundle:
  stage: bundle
  before_script:
    - ruby -v  # Print out ruby version for debugging
    - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby
    - chmod +x ./_script/cibuild  # or do this locally and commit
  script:
    - ./_script/cibuild
