language: ruby
rvm:
  - 2.3.3

before_script:
  - chmod +x ./_script/cibuild # or do this locally and commit

script: ./_script/cibuild

addons:
  ssh_known_hosts: jannisfink.de

before_deploy:
  - openssl aes-256-cbc -K $encrypted_dfe6a32c49b7_key -iv $encrypted_dfe6a32c49b7_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/_dist travisci@jannisfink.de:/home/travisci/jannisfink.de
  on:
    branch: master
